### PR TITLE
node.js classifiers: Fix fallback to wasm mode

### LINKED ISSUE #267: Failed to Classify - Nodejs module not found
**Describe the bug**
I have installed the app from the store.
The first time I tried to use it, it was missing the path to 'node' and crashed. After I entered its path manually, the detection started, but then crashed with the following stacktrace. I can't find a suitable solution to this problem unfortunately. Ideas? Tried a lot, installed it manually, removed it a couple times, reinstalled node/npm....

**Recognize (please complete the following information):**
 - JS-only mode: both
  - Enabled modes: object detection

**Server (please complete the following information):**
 - Nextcloud: 24.0.4
 - OS: AlmaLinux 8 (RHEL)
 - RAM: 4GB
 - Processor Architecture: QEMU Virtual CPU version 2.5+ (2 cores)
 - nodejs version: 14 
 - npm version 6xx

```console
Running array (
  0 => '/usr/bin/node',
  1 => '/var/www/nextcloud/apps/recognize/src/classifier_imagenet.js',
  2 => '-',
)
Classifier process output: Error: The Node.js native addon module (tfjs_binding.node) can not be found at path: /var/www/nextcloud/apps/recognize/node_modules/@tensorflow/tfjs-node/lib/napi-v8/tfjs_binding.node.
Please run command 'npm rebuild @tensorflow/tfjs-node --build-addon-from-source' to rebuild the native addon module.
If you have problem with building the addon module, please check https://github.com/tensorflow/tfjs/blob/master/tfjs-node/WINDOWS_TROUBLESHOOTING.md or file an issue.
    at Object.<anonymous> (/var/www/nextcloud/apps/recognize/node_modules/@tensorflow/tfjs-node/dist/index.js:49:11)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/var/www/nextcloud/apps/recognize/src/classifier_imagenet.js:23:9)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)

Classifier process output: Trying js-only mode

Classifier process output: Error: The Node.js native addon module (tfjs_binding.node) can not be found at path: /var/www/nextcloud/apps/recognize/node_modules/@tensorflow/tfjs-node/lib/napi-v8/tfjs_binding.node.
Please run command 'npm rebuild @tensorflow/tfjs-node --build-addon-from-source' to rebuild the native addon module.
If you have problem with building the addon module, please check https://github.com/tensorflow/tfjs/blob/master/tfjs-node/WINDOWS_TROUBLESHOOTING.md or file an issue.
    at Object.<anonymous> (/var/www/nextcloud/apps/recognize/node_modules/@tensorflow/tfjs-node/dist/index.js:49:11)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/var/www/nextcloud/apps/recognize/src/efficientnet/EfficientnetModel.js:9:8)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
Trying js-only mode

Classifier process output: Error: Backend name 'tensorflow' not found in registry
    at Engine.<anonymous> (/var/www/nextcloud/apps/recognize/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4238:35)
    at step (/var/www/nextcloud/apps/recognize/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:123:27)
    at Object.next (/var/www/nextcloud/apps/recognize/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:72:53)
    at /var/www/nextcloud/apps/recognize/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:65:71
    at new Promise (<anonymous>)
    at __awaiter (/var/www/nextcloud/apps/recognize/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:51:12)
    at Engine.setBackend (/var/www/nextcloud/apps/recognize/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4232:16)
    at Object.setBackend (/var/www/nextcloud/apps/recognize/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:10577:19)
    at Object.<anonymous> (/var/www/nextcloud/apps/recognize/src/classifier_imagenet.js:175:4)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)

Classifier process output: Error: The Node.js native addon module (tfjs_binding.node) can not be found at path: /var/www/nextcloud/apps/recognize/node_modules/@tensorflow/tfjs-node/lib/napi-v8/tfjs_binding.node.
Please run command 'npm rebuild @tensorflow/tfjs-node --build-addon-from-source' to rebuild the native addon module.
If you have problem with building the addon module, please check https://github.com/tensorflow/tfjs/blob/master/tfjs-node/WINDOWS_TROUBLESHOOTING.md or file an issue.
    at Object.<anonymous> (/var/www/nextcloud/apps/recognize/node_modules/@tensorflow/tfjs-node/dist/index.js:49:11)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/var/www/nextcloud/apps/recognize/src/classifier_imagenet.js:23:9)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
Trying js-only mode
Error: The Node.js native addon module (tfjs_binding.node) can not be found at path: /var/www/nextcloud/apps/recognize/node_modules/@tensorflow/tfjs-node/lib/napi-v8/tfjs_binding.node.
Please run command 'npm rebuild @tensorflow/tfjs-node --build-addon-from-source' to rebuild the native addon module.
If you have problem with building the addon module, please check https://github.com/tensorflow/tfjs/blob/master/tfjs-node/WINDOWS_TROUBLESHOOTING.md or file an issue.
    at Object.<anonymous> (/var/www/nextcloud/apps/recognize/node_modules/@tensorflow/tfjs-node/dist/index.js:49:11)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/var/www/nextcloud/apps/recognize/src/efficientnet/EfficientnetModel.js:9:8)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
Trying js-only mode
Error: Backend name 'tensorflow' not found in registry
    at Engine.<anonymous> (/var/www/nextcloud/apps/recognize/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4238:35)
    at step (/var/www/nextcloud/apps/recognize/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:123:27)
    at Object.next (/var/www/nextcloud/apps/recognize/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:72:53)
    at /var/www/nextcloud/apps/recognize/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:65:71
    at new Promise (<anonymous>)
    at __awaiter (/var/www/nextcloud/apps/recognize/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:51:12)
    at Engine.setBackend (/var/www/nextcloud/apps/recognize/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4232:16)
    at Object.setBackend (/var/www/nextcloud/apps/recognize/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:10577:19)
    at Object.<anonymous> (/var/www/nextcloud/apps/recognize/src/classifier_imagenet.js:175:4)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)

Failed to classify images
Classifier process error
```

### PR DESCRIPTION
**Pull request by marcelklehr**
fixes #267

### CODE REVIEW

File: src/classifier_facevectors.js [hunk 1]
```diff
@@ -77,7 +77,7 @@ async function main() {
 	}
 }
 
-tf.setBackend(process.env.RECOGNIZE_PUREJS === 'true' ? 'wasm' : 'tensorflow')
```
Comment (marcelklehr) [inline src/classifier_facevectors.js:80]: Only checking the env var is not enough, because if loading tf-node fails we want to switch to wasm dynamically

**Review by juliushaertl — APPROVED** [review]
