### PR TITLE
Zero safety

### LINKED ISSUE #397: Division by zero in FaceClusterAnalyzer
Log is full of these, i'm on current tip (3.1.0)
```
{
   "reqId":"61ePx0Iyhsx6SnCldmJ6",
   "level":3,
   "time":"2022-10-19T12:48:02+00:00",
   "remoteAddr":"",
   "user":"--",
   "app":"PHP",
   "method":"",
   "url":"--",
   "message":"Division by zero at /var/www/nextcloud/apps/recognize/lib/Service/FaceClusterAnalyzer.php#190",
   "userAgent":"--",
   "version":"25.0.0.18",
   "exception":{
      "Exception":"Error",
      "Message":"Division by zero at /var/www/nextcloud/apps/recognize/lib/Service/FaceClusterAnalyzer.php#190",
      "Code":0,
      "Trace":[
         {
            "file":"/var/www/nextcloud/apps/recognize/lib/Service/FaceClusterAnalyzer.php",
            "line":190,
            "function":"onError",
            "class":"OC\\Log\\ErrorHandler",
            "type":"::"
         },
         {
            "function":"OCA\\Recognize\\Service\\{closure}",
            "class":"OCA\\Recognize\\Service\\FaceClusterAnalyzer",
            "type":"::",
            "args":[
               "*** sensitive parameters replaced ***"
            ]
         },
         {
            "file":"/var/www/nextcloud/apps/recognize/lib/Service/FaceClusterAnalyzer.php",
            "line":189,
            "function":"array_map"
         },
         {
            "file":"/var/www/nextcloud/apps/recognize/lib/Service/FaceClusterAnalyzer.php",
            "line":90,
            "function":"calculateCentroidOfDetections",
            "class":"OCA\\Recognize\\Service\\FaceClusterAnalyzer",
            "type":"::"
         },
         {
            "file":"/var/www/nextcloud/apps/recognize/lib/BackgroundJobs/ClusterFacesJob.php",
            "line":28,
            "function":"calculateClusters",
            "class":"OCA\\Recognize\\Service\\FaceClusterAnalyzer",
            "type":"->"
         },
         {
            "file":"/var/www/nextcloud/lib/public/BackgroundJob/Job.php",
            "line":78,
            "function":"run",
            "class":"OCA\\Recognize\\BackgroundJobs\\ClusterFacesJob",
            "type":"->"
         },
         {
            "file":"/var/www/nextcloud/lib/public/BackgroundJob/QueuedJob.php",
            "line":58,
            "function":"start",
            "class":"OCP\\BackgroundJob\\Job",
            "type":"->"
         },
         {
            "file":"/var/www/nextcloud/lib/public/BackgroundJob/QueuedJob.php",
            "line":48,
            "function":"start",
            "class":"OCP\\BackgroundJob\\QueuedJob",
            "type":"->"
         },
         {
            "file":"/var/www/nextcloud/cron.php",
            "line":152,
            "function":"execute",
            "class":"OCP\\BackgroundJob\\QueuedJob",
            "type":"->"
         }
      ],
      "File":"/var/www/nextcloud/lib/private/Log/ErrorHandler.php",
      "Line":92,
      "CustomMessage":"--"
   }
}
```

I'll try to get some more info when i have time

### PR DESCRIPTION
**Pull request by marcelklehr**
fixes #397

### CODE REVIEW

**Review by julien-nc — APPROVED** [review]
Only understood the parts avoiding the division by zero...

File: lib/Dav/Faces/FacePhoto.php [hunk 1]
```diff
@@ -51,12 +51,14 @@ public function getName() {
...
 		$detections = $this->detectionMapper->findByClusterId($this->faceDetection->getClusterId());
-		$centroid = FaceClusterAnalyzer::calculateCentroidOfDetections($detections);
-		$distance = new Euclidean();
-		$distanceValue = $distance->compute($centroid, $this->faceDetection->getVector());
+		if (count($detections) > 1) {
+			$centroid = FaceClusterAnalyzer::calculateCentroidOfDetections($detections);
+			$distance = new Euclidean();
+			$distanceValue = $distance->compute($centroid, $this->faceDetection->getVector());
+			// Set threshold to avoid recreating the same mistake
+			$this->faceDetection->setThreshold($distanceValue);
```
Comment (marcelklehr) [inline lib/Dav/Faces/FacePhoto.php:59]: Here we only want to calculate and set a threshold if there's more than the one face in the cluster, otherwise we do a useless calculation.

File: lib/Service/FaceClusterAnalyzer.php [hunk 2]
```diff
@@ -107,7 +107,8 @@ public function calculateClusters(string $userId) {
 				/** @var FaceDetection $detection */
 				$detection = $item[0];
 				$distance = new Euclidean();
-				if ($detection->getThreshold() > 0.0) {
+				// If threshold is larger than 0 and $clusterCentroid is not the null vector
+				if ($detection->getThreshold() > 0.0 && count(array_filter($clusterCentroid, fn($el) => $el !== 0.0)) > 0) {
```
Comment (marcelklehr) [inline lib/Service/FaceClusterAnalyzer.php:111]: If the centroid could not be calculated, because there were zero detections in the cluster (see below), the centroid will be the null vector (`count(array_filter($clusterCentroid, fn($el) => $el !== 0.0)) > 0` checks if it is not the null vector). Then we don't want to apply the threshold either.

Comment (julien-nc) [reply lib/Service/FaceClusterAnalyzer.php:111]: Thanks for the explanations.
