### PR TITLE
InstallDeps: Use IClient to download node

### LINKED ISSUE #262: App install and run do not work behind proxy
**Describe the bug**
App partly not install if nc behind a proxy

**To Reproduce**
try app install behind proxy, e.g. node is not in the designed directory

**Expected behavior**
recognize should be ably to detect global proxy configuration, e.g. in config.php

**Server (please complete the following information):**
 - Nextcloud: [e.g. 21.0.4] 24.0.3
 - OS: [e.g. iOS] Debian Linux 11
 - RAM: [e.g. 16GB] 16 GB
 - Processor Architecture [e.g. x86, ARM64, etc. ] amd64

### PR DESCRIPTION
**Pull request by marcelklehr**
fixes #262

### CODE REVIEW

File: lib/Migration/InstallDeps.php [hunk 1]
```diff
@@ -147,14 +150,11 @@ protected function downloadNodeBinary(string $server, string $version, string $a
 		}
 		$url = $server.$version.'/'.$name.'.tar.gz';
 		$file = $this->binaryDir.'/'.$arch.'.tar.gz';
-		$archive = file_get_contents($url);
-		if ($archive === false) {
+		try {
+			$this->clientService->newClient()->get($url, ['timeout' => 60, 'sink' => $file]);
+		} catch (\Exception $e) {
 			throw new \Exception('Downloading of node binary failed');
```
Comment (juliushaertl) [inline lib/Migration/InstallDeps.php:156]: Might be worth to log the exception to have more details in case of a failure

**Review by juliushaertl — CHANGES_REQUESTED** [review]
Small comment about logging, otherwise looks good 👍
